<!DOCTYPE tiles-definitions
    [
        <!ELEMENT component-definitions (definition+)>
        <!ELEMENT tiles-definitions (definition+)>
        <!ELEMENT definition (put*, putList*)>
        <!ATTLIST definition
            name CDATA #REQUIRED
            page CDATA #IMPLIED
            path CDATA #IMPLIED
            extends CDATA #IMPLIED
            role CDATA #IMPLIED
            template CDATA #IMPLIED
            controllerClass CDATA #IMPLIED
            controllerUrl CDATA #IMPLIED>
        <!ELEMENT put (#PCDATA)>
        <!ATTLIST put
            name CDATA #REQUIRED
            value CDATA #IMPLIED
            type (string | page | template | definition) #IMPLIED
            content CDATA #IMPLIED
            direct (true | false) #IMPLIED>
        <!ELEMENT putList ( (add* | item* | bean* | putList*)+) >
        <!ATTLIST putList
            name CDATA #REQUIRED>
        <!ELEMENT putListElements (add | item | bean)>
        <!ELEMENT add (#PCDATA)>
        <!ATTLIST add
            value CDATA #IMPLIED
            type (string | page | template | definition) #IMPLIED
            content CDATA #IMPLIED
            direct (true | false) #IMPLIED>
        <!ELEMENT bean (#PCDATA)>
        <!ATTLIST bean
            classtype CDATA #REQUIRED>
        <!ELEMENT item (#PCDATA)>
        <!ATTLIST item
            value CDATA #REQUIRED
            link CDATA #REQUIRED
            classtype CDATA #IMPLIED
            icon CDATA #IMPLIED
            tooltip CDATA #IMPLIED>
    ]>

<tiles-definitions>
 

    <definition name="layout.singularity" path="/jsp/template/template.jsp" >
        <put name="title" value="Singularity" />
        <put name="header" value="/jsp/common/header.jsp" />
        <put name="menu" value="/jsp/common/navbar.jsp" />
        <put name="body" value="/jsp/body/infobody.jsp" />
        <put name="tabOne" value="/jsp/body/infobody.jsp" />
        <put name="tabOneTitle" value="" />
        <put name="tabTwo" value="/jsp/body/infobody.jsp" />
        <put name="tabTwoTitle" value="" />
        <put name="tabThree" value="/jsp/body/infobody.jsp" />
        <put name="tabThreeTitle" value="" />
        <put name="tabFour" value="/jsp/body/infobody.jsp" />
        <put name="tabFourTitle" value="" />
        <put name="script" value="/dummy.jsp" />
        <put name="ie-script" value="/dummy.jsp" />
      
    </definition>


     <definition name="/jsp/body/deviceProfile.tiles" extends="layout.singularity" >
        <put name="title" value="Device Profile Admin" />
        <put name="body" value="/jsp/body/deviceProfileList.jsp" />
        <put name="tabOneTitle" value="Detail" />
        <put name="tabOne" value="/jsp/body/deviceProfile.jsp" />
        <put name="tabTwoTitle" value="Sensors" />
        <put name="tabTwo" value="/jsp/body/deviceProfileSensors.jsp" />
        <put name="tabThreeTitle" value="Readers" />
        <put name="tabThree" value="/jsp/body/deviceProfileReaders.jsp" />
    </definition>

    <definition name="/jsp/body/logicalDevice.tiles" extends="layout.singularity" >
        <put name="title" value="Logical Device" />
        <put name="body" value="/jsp/body/logicalDeviceList.jsp" />
        <put name="tabOneTitle" value="Detail" />
        <put name="tabOne" value="/jsp/body/logicalDevice.jsp" />
    </definition>

    <definition name="/jsp/body/ecSpec.tiles" extends="layout.singularity" >
        <put name="title" value="ALE Define" />
        <put name="body" value="/jsp/body/ecSpecList.jsp" />
        <put name="tabOne" value="/jsp/body/ecSpecDefine.jsp" />
        <put name="tabOneTitle" value="Detail" />
    </definition>

    <definition name="/jsp/body/ecSpecSubscribe.tiles" extends="layout.singularity" >
        <put name="title" value="ALE Subscription" />
        <put name="infoPane" value="/jsp/body/ecSpecSubscribe.jsp" />
    </definition>

  
    <definition name="/jsp/body/carterNote.tiles" extends="layout.singularity" >
        <put name="title" value="Carter Note" />
        <put name="body" value="/jsp/body/carterNoteList.jsp" />
        <put name="tabOne" value="/jsp/body/carterNote.jsp" />
    </definition>
   
    <definition name="/jsp/body/carterNoteList.tiles" extends="layout.singularity" >
        <put name="body" value="/jsp/body/carterNoteList.jsp" />
    </definition>
   
    <definition name="/jsp/body/welcome.tiles" extends="layout.singularity" >
        <put name="body" value="/jsp/body/welcome.jsp" />
    </definition>
   
    
    <definition name="/jsp/body/viewer.tiles" path="/jsp/body/viewer.jsf" >
        <put name="tbody" value="/jsp/body/readerMgmt.jsp" />
        <put name="title" value="Test Reader Mgmt" />
    </definition>
    
    <definition name="/jsp/body/eventMonitorWrap.tiles" extends="layout.singularity" >
        <put name="title" value="Event Monitor" />
        <put name="body" value="/jsp/body/eventMonitor.jsp" />
        <put name="tabOneTitle" value="Detail" />
        <put name="tabOne" value="/jsp/body/carterNote.jsp" />
        <put name="tabTwoTitle" value="Map" />
        <put name="tabTwo" value="/jsp/body/map.jsp" />
        <put name="script" value="/script.jsp" />
        <put name="googleMaps" value="true" />
    </definition>
    
    <definition name="/jsp/body/eventRecordArchive.tiles" extends="layout.singularity" >
        <put name="title" value="Event Archive" />
        <put name="body" value="/jsp/body/eventRecordArchive.jsp" />
        <put name="tabOneTitle" value="Carter Note" />
        <put name="tabOne" value="/jsp/body/carterNote.jsp" />
        <put name="tabTwoTitle" value="Event Record Detail" />
        <put name="tabTwo" value="/jsp/body/eventRecord.jsp" />
    </definition>
    
    <definition name="/jsp/body/tag.tiles" extends="layout.singularity" >
        <put name="title" value="Tag Entry" />
        <put name="body" value="/jsp/body/tagList.jsp" />
        <put name="tabOne" value="/jsp/body/tag.jsp" />
        <put name="tabOneTitle" value="Detail" />
    </definition>
 
    <definition name="/jsp/body/notavailable.tiles" extends="layout.singularity" >
        <put name="title" value="Future Feature" />
        <put name="infoPane" value="/jsp/body/notavailable.jsp" />
    </definition>

    <definition name="/jsp/body/map.tiles" extends="layout.singularity" >
        <put name="title" value="Singularity Maps" />
        <put name="body" value="/jsp/body/map.jsp" />
    </definition>
    
 </tiles-definitions>
